- hosts: webserver
  tasks:
    - name: install python-docker
      yum:
        name: python-docker
        state: present
      when:
        - ansible_distribution == "CentOS"
    - name: install python-docker
      apt:
        name : python-docker
        state: present
      when:
        - ansible_distribution == "Ubuntu"
    - name: run container
      docker_container:
        name: apache2
        state: present
        images: taqykimura/httpd:5
        published_port:
          - 8082:80
